name: flutter_fire_auth
description: A authentication Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_core: ^2.12.0
  get: ^4.6.5
  font_awesome_flutter: 10.4.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/img/


