// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPFCShwtWBEK9XrxbUvYVeHCmumLgi9U',
    appId: '1:408178090013:web:2861be04ee7ab0722166f4',
    messagingSenderId: '408178090013',
    projectId: 'fluttefireauth',
    authDomain: 'fluttefireauth.firebaseapp.com',
    storageBucket: 'fluttefireauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9RQZgnI7nwxwL0Qss0n8IpEyociR_f8',
    appId: '1:408178090013:android:2a4b0da1a759cc9a2166f4',
    messagingSenderId: '408178090013',
    projectId: 'fluttefireauth',
    storageBucket: 'fluttefireauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ZWLE5rRG5K9AiP9azFDy05upbXu93X8',
    appId: '1:408178090013:ios:e3aad66db1283a9a2166f4',
    messagingSenderId: '408178090013',
    projectId: 'fluttefireauth',
    storageBucket: 'fluttefireauth.appspot.com',
    iosClientId: '408178090013-qbelt331o0cfjp198te0ijo4srtspd39.apps.googleusercontent.com',
    iosBundleId: 'com.baguskto.flutterFireAuth',
  );
}
